{"name": "test_update_user_by_id", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\jothi\\\\Documents\\\\api-testing-repo\\\\tests\\\\test_data.json'", "trace": "cls = <class 'management_user.TestManagementUserAuth'>\n\n    @classmethod\n    def setUpClass(cls):\n        cls.api = ManagementUserAPIHandler(base_url=\"http://localhost:8000\")\n        json_path = os.path.join(os.path.dirname(__file__), \"test_data.json\")\n    \n>       with open(json_path, \"r\") as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\jothi\\\\Documents\\\\api-testing-repo\\\\tests\\\\test_data.json'\n\nmanagement_user.py:17: FileNotFoundError"}, "start": 1754042418924, "stop": 1754042418924, "uuid": "6de81909-076c-468c-9c73-a4b50a3d4465", "historyId": "d67f1f3ad0371ad488648f5fdd4efc0a", "testCaseId": "d67f1f3ad0371ad488648f5fdd4efc0a", "fullName": "tests.management_user.TestManagementUserAuth#test_update_user_by_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "5044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}