{"name": "test_gym_logout", "status": "failed", "statusDetails": {"message": "Failed: Gym logout test failed: 'dict' object has no attribute 'status_code'", "trace": "self = <test_gym_management.TestGymManagement object at 0x0000024E98E16E30>\napi = <tests.utils.api_helper1.ManagementUserAPIHandler object at 0x0000024E98E9C400>\ngym_auth_tokens = {'access_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huLmRvZTJAZ3ltLmNvbSIsImlkIjoiOGM0YjQ1NTItY2U0Mi0...mNvbSIsImF1ZCI6Imh0dHBzOi8veW91cmFwcC5jb20vYXBpIiwidHlwZSI6InJlZnJlc2gifQ.izZPyxxGFkRlsC93CjEz9C7m15jXRTp2osKTB6aGo6g'}\n\n    def test_gym_logout(self, api, gym_auth_tokens):\n        \"\"\"Test logging out the gym user.\"\"\"\n        try:\n>           status_code = api.gym_logout(token=gym_auth_tokens[\"access_token\"])\n\ntest_gym_management.py:238: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <tests.utils.api_helper1.ManagementUserAPIHandler object at 0x0000024E98E9C400>\ntoken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huLmRvZTJAZ3ltLmNvbSIsImlkIjoiOGM0YjQ1NTItY2U0Mi00N2RlLWFlNDYtNTIy...BwLmNvbSIsImF1ZCI6Imh0dHBzOi8veW91cmFwcC5jb20vYXBpIiwidHlwZSI6ImFjY2VzcyJ9.5f0JvETvPWCCSA7RLTidbma8YlKa-DNcpsbaEP3zGbk'\n\n    def gym_logout(self, token: str):\n        \"\"\"\n        Log out a gym user.\n    \n        Args:\n            token (str): Bearer JWT access token.\n    \n        Returns:\n            int: HTTP status code.\n        \"\"\"\n        endpoint = f\"/api/{self.api_version}/gym/auth/logout\"\n        log.info(f\"Logging out gym user | Endpoint: {endpoint}\")\n        try:\n            resp = self.get(endpoint, token=token)\n>           log.info(f\"Gym user logout response | Status: {resp.status_code}\")\nE           AttributeError: 'dict' object has no attribute 'status_code'\n\nutils\\api_helper1.py:899: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_gym_management.TestGymManagement object at 0x0000024E98E16E30>\napi = <tests.utils.api_helper1.ManagementUserAPIHandler object at 0x0000024E98E9C400>\ngym_auth_tokens = {'access_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huLmRvZTJAZ3ltLmNvbSIsImlkIjoiOGM0YjQ1NTItY2U0Mi0...mNvbSIsImF1ZCI6Imh0dHBzOi8veW91cmFwcC5jb20vYXBpIiwidHlwZSI6InJlZnJlc2gifQ.izZPyxxGFkRlsC93CjEz9C7m15jXRTp2osKTB6aGo6g'}\n\n    def test_gym_logout(self, api, gym_auth_tokens):\n        \"\"\"Test logging out the gym user.\"\"\"\n        try:\n            status_code = api.gym_logout(token=gym_auth_tokens[\"access_token\"])\n            assert status_code == 200\n        except Exception as e:\n>           pytest.fail(f\"Gym logout test failed: {e}\")\nE           Failed: Gym logout test failed: 'dict' object has no attribute 'status_code'\n\ntest_gym_management.py:241: Failed"}, "description": "Test logging out the gym user.", "attachments": [{"name": "log", "source": "c6197f8b-a7c3-4348-abc1-7a334507c3d1-attachment.txt", "type": "text/plain"}], "start": 1754396712819, "stop": 1754396712919, "uuid": "58453f36-2c9f-42ef-8302-74df6c3f6613", "historyId": "dfcbb26e19adadd1d0acf679ac9fd58f", "testCaseId": "dfcbb26e19adadd1d0acf679ac9fd58f", "fullName": "tests.test_gym_management.TestGymManagement#test_gym_logout", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_gym_management"}, {"name": "subSuite", "value": "TestGymManagement"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "22908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_gym_management"}], "titlePath": ["tests", "test_gym_management.py", "TestGymManagement"]}