{"name": "test_get_user_by_id", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'TestManagementUserAuth' has no attribute 'test_data1'. Did you mean: 'test_data'?", "trace": "cls = <class 'management_user.TestManagementUserAuth'>\n\n    @classmethod\n    def setUpClass(cls):\n        cls.api = ManagementUserAPIHandler(base_url=\"http://localhost:8000\")\n        json_path = os.path.join(os.path.dirname(__file__), '../utils/test_data1.json')\n    \n        with open(json_path, \"r\") as file:\n            cls.test_data = json.load(file)\n    \n>       cls.email = cls.test_data1[\"login\"][0][\"email\"]\nE       AttributeError: type object 'TestManagementUserAuth' has no attribute 'test_data1'. Did you mean: 'test_data'?\n\nmanagement_user.py:20: AttributeError"}, "start": 1754042494602, "stop": 1754042494602, "uuid": "2dda8bef-9575-4bbf-adeb-cbd92f3dbf12", "historyId": "c74391dc0149f166a4375d1eace4baa7", "testCaseId": "c74391dc0149f166a4375d1eace4baa7", "fullName": "tests.management_user.TestManagementUserAuth#test_get_user_by_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "4304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}