{"name": "test_update_user_by_id", "status": "failed", "statusDetails": {"message": "AssertionError: <Response [401]> is not an instance of <class 'dict'>", "trace": "self = <management_user.TestManagementUserAuth testMethod=test_update_user_by_id>\n\n    def test_update_user_by_id(self):\n        update_payload = {\"full_name\": \"Updated User\"}\n        response = self.api.update_user_by_id(\n            user_id=self.user_id,\n            token=self.access_token,\n            update_payload=update_payload\n        )\n>       self.assertIsInstance(response, dict)\nE       AssertionError: <Response [401]> is not an instance of <class 'dict'>\n\nmanagement_user.py:111: AssertionError"}, "start": 1754043632517, "stop": 1754043632563, "uuid": "56929bdb-1d8b-4d4b-82a6-3a82740c8123", "historyId": "d67f1f3ad0371ad488648f5fdd4efc0a", "testCaseId": "d67f1f3ad0371ad488648f5fdd4efc0a", "fullName": "tests.management_user.TestManagementUserAuth#test_update_user_by_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "8388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}