{"name": "test_get_user_by_id", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\jothi\\\\Documents\\\\api-testing-repo\\\\tests\\\\test_data.json'", "trace": "cls = <class 'management_user.TestManagementUserAuth'>\n\n    @classmethod\n    def setUpClass(cls):\n        cls.api = ManagementUserAPIHandler(base_url=\"http://localhost:8000\")\n        json_path = os.path.join(os.path.dirname(__file__), \"test_data.json\")\n    \n>       with open(json_path, \"r\") as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\jothi\\\\Documents\\\\api-testing-repo\\\\tests\\\\test_data.json'\n\nmanagement_user.py:17: FileNotFoundError"}, "start": 1754042418825, "stop": 1754042418825, "uuid": "77011745-aa7a-4630-94dd-2764a08c98c3", "historyId": "c74391dc0149f166a4375d1eace4baa7", "testCaseId": "c74391dc0149f166a4375d1eace4baa7", "fullName": "tests.management_user.TestManagementUserAuth#test_get_user_by_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "5044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}