ERROR    tests.utils.api_client:api_client.py:54 API Error [422]: {'detail': [{'type': 'missing', 'loc': ['body', 'first_name'], 'msg': 'Field required', 'input': {'user_data': {'first_name': 'New', 'last_name': 'User', 'email': 'newuse1@example.com', 'phone_number': '+1234567890', 'password': 'SecurePass123'}, 'expected_status': 201}}, {'type': 'missing', 'loc': ['body', 'last_name'], 'msg': 'Field required', 'input': {'user_data': {'first_name': 'New', 'last_name': 'User', 'email': 'newuse1@example.com', 'phone_number': '+1234567890', 'password': 'SecurePass123'}, 'expected_status': 201}}, {'type': 'missing', 'loc': ['body', 'email'], 'msg': 'Field required', 'input': {'user_data': {'first_name': 'New', 'last_name': 'User', 'email': 'newuse1@example.com', 'phone_number': '+1234567890', 'password': 'SecurePass123'}, 'expected_status': 201}}, {'type': 'missing', 'loc': ['body', 'password'], 'msg': 'Field required', 'input': {'user_data': {'first_name': 'New', 'last_name': 'User', 'email': 'newuse1@example.com', 'phone_number': '+1234567890', 'password': 'SecurePass123'}, 'expected_status': 201}}]} | Exception: 422 Client Error: Unprocessable Entity for url: http://localhost:8000/api/v1/gym/auth/register
ERROR    tests.utils.api_helper1:api_helper1.py:779 Failed to create gym user: 422 Client Error: Unprocessable Entity for url: http://localhost:8000/api/v1/gym/auth/register