{"name": "test_verify_email", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\jothi\\\\Documents\\\\api-testing-repo\\\\tests\\\\test_data.json'", "trace": "cls = <class 'management_user.TestManagementUserAuth'>\n\n    @classmethod\n    def setUpClass(cls):\n        cls.api = ManagementUserAPIHandler(base_url=\"http://localhost:8000\")\n        json_path = os.path.join(os.path.dirname(__file__), \"test_data.json\")\n    \n>       with open(json_path, \"r\") as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\jothi\\\\Documents\\\\api-testing-repo\\\\tests\\\\test_data.json'\n\nmanagement_user.py:17: FileNotFoundError"}, "start": 1754042418936, "stop": 1754042418936, "uuid": "695e7048-ae6d-4be3-bd29-83d68b11b922", "historyId": "5dcef521107a554b16339fd9d6c0f954", "testCaseId": "5dcef521107a554b16339fd9d6c0f954", "fullName": "tests.management_user.TestManagementUserAuth#test_verify_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "5044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}