{"name": "test_resend_verification", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\jothi\\\\Documents\\\\api-testing-repo\\\\tests\\\\test_data.json'", "trace": "cls = <class 'management_user.TestManagementUserAuth'>\n\n    @classmethod\n    def setUpClass(cls):\n        cls.api = ManagementUserAPIHandler(base_url=\"http://localhost:8000\")\n        json_path = os.path.join(os.path.dirname(__file__), \"test_data.json\")\n    \n>       with open(json_path, \"r\") as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\jothi\\\\Documents\\\\api-testing-repo\\\\tests\\\\test_data.json'\n\nmanagement_user.py:17: FileNotFoundError"}, "start": 1754042418899, "stop": 1754042418899, "uuid": "267b24f2-d458-4867-b851-a7092b06e64c", "historyId": "1c64ed79e472e67dcd6d08919caa252a", "testCaseId": "1c64ed79e472e67dcd6d08919caa252a", "fullName": "tests.management_user.TestManagementUserAuth#test_resend_verification", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "5044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}