{"name": "test_reset_password", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'TestManagementUserAuth' has no attribute 'test_data1'. Did you mean: 'test_data'?", "trace": "cls = <class 'management_user.TestManagementUserAuth'>\n\n    @classmethod\n    def setUpClass(cls):\n        cls.api = ManagementUserAPIHandler(base_url=\"http://localhost:8000\")\n        json_path = os.path.join(os.path.dirname(__file__), '../utils/test_data1.json')\n    \n        with open(json_path, \"r\") as file:\n            cls.test_data = json.load(file)\n    \n>       cls.email = cls.test_data1[\"login\"][0][\"email\"]\nE       AttributeError: type object 'TestManagementUserAuth' has no attribute 'test_data1'. Did you mean: 'test_data'?\n\nmanagement_user.py:20: AttributeError"}, "start": 1754042494722, "stop": 1754042494722, "uuid": "123c079f-37c1-4fa8-8831-554896b911c1", "historyId": "bb47708e7a4f514e6b4ad14af8a364cc", "testCaseId": "bb47708e7a4f514e6b4ad14af8a364cc", "fullName": "tests.management_user.TestManagementUserAuth#test_reset_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "management_user"}, {"name": "subSuite", "value": "TestManagementUserAuth"}, {"name": "host", "value": "mirrajo"}, {"name": "thread", "value": "4304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.management_user"}], "titlePath": ["tests", "management_user.py", "TestManagementUserAuth"]}